'use strict';
const $ = id => document.getElementById(id);
const params = new URLSearchParams(location.hash.slice(1));
const token = params.get('token') || sessionStorage.getItem('cosmos-token') || '';
if (token) sessionStorage.setItem('cosmos-token', token);
history.replaceState(null, '', location.pathname);
const state = {files: new Map(), active: null, provider: 'codex', histories: {codex: [], gemini: []}, chats: {codex: [], gemini: []}, team: [], reports: {}, run: null, chat: null, teamJob: null, teamDirty: false};
let toastTimer;
function toast(message, error=false) { $('toast').textContent=message; $('toast').className=error?'error':''; $('toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').hidden=true,6000); }
async function api(path, data) { const response=await fetch(path,{method:data?'POST':'GET',headers:{'X-IDE-Token':token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined}); const result=await response.json(); if(!response.ok) throw new Error(result.error || 'Ошибка запроса'); return result; }
function guarded(fn) { return (...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>toast(e.message,true)); }
function el(tag, className='', text='') {const node=document.createElement(tag);node.className=className;node.textContent=text;return node;}
function activeFile(){return state.files.get(state.active);}
function switchView(team){$('teamView').hidden=!team;$('editorView').hidden=team;$('teamMode').classList.toggle('active',team);$('filesMode').classList.toggle('active',!team);}
async function tree(container,path='',depth=0){const items=await api('/api/tree?path='+encodeURIComponent(path));container.replaceChildren();for(const item of items){const row=el('div','tree-row');row.style.paddingLeft=(12+depth*13)+'px';const icon=el('span','tree-icon'+(item.dir?' tree-folder':''),item.dir?'›':item.name.endsWith('.py')?'py':'◇');row.append(icon,el('span','',item.name));container.append(row);if(item.dir){const sub=el('div');sub.hidden=true;container.append(sub);row.onclick=guarded(async()=>{if(sub.hidden){await tree(sub,item.path,depth+1);sub.hidden=false;icon.textContent='⌄';}else{sub.hidden=true;icon.textContent='›';}});}else{row.dataset.path=item.path;row.classList.toggle('active',item.path===state.active);row.onclick=guarded(()=>openFile(item.path));}}}
function renderTabs(){const tabs=$('tabs');tabs.replaceChildren();for(const [path,file] of state.files){const tab=el('div','tab'+(state.active===path?' selected':''));tab.append(el('span','tree-icon',path.endsWith('.py')?'py':'◇'),el('span','',path.split('/').pop()+(file.dirty?' ●':'')));const close=el('button','','×');close.title='Закрыть файл';close.onclick=e=>{e.stopPropagation();if(file.dirty&&!confirm('Закрыть файл без сохранения?'))return;state.files.delete(path);if(state.active===path){state.active=null;const next=state.files.keys().next().value;if(next)selectFile(next);else showEmpty();}renderTabs();};tab.append(close);tab.onclick=()=>selectFile(path);tabs.append(tab);}if(!state.files.size)tabs.append(el('span','empty-tab','Начните с файла'));}
function showEmpty(){$('welcome').hidden=false;$('codeArea').hidden=true;$('breadcrumb').textContent='Рабочее пространство';$('contextName').textContent='Без файла';}
function selectFile(path){state.active=path;const file=activeFile();$('code').value=file.content;$('welcome').hidden=true;$('codeArea').hidden=false;$('breadcrumb').textContent=path;$('contextName').textContent=path.split('/').pop();switchView(false);highlight();renderTabs();document.querySelectorAll('.tree-row[data-path]').forEach(n=>n.classList.toggle('active',n.dataset.path===path));}
async function openFile(path){if(!state.files.has(path)){const file=await api('/api/file?path='+encodeURIComponent(path));state.files.set(path,{...file,dirty:false});}selectFile(path);}
function escapeHTML(text){return text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function highlight(){const code=$('code').value;const regex=/(#[^\n]*|"""[\s\S]*?"""|'''[\s\S]*?'''|"(?:\\.|[^"\\\n])*"|'(?:\\.|[^'\\\n])*'|\b(?:def|class|return|import|from|as|if|elif|else|for|while|in|not|and|or|is|None|True|False|try|except|finally|with|yield|async|await|pass|raise|lambda|break|continue|assert|global|nonlocal|del)\b|\b\d+(?:\.\d+)?\b)/g;let html='',last=0;for(const match of code.matchAll(regex)){html+=escapeHTML(code.slice(last,match.index));const value=match[0], cls=value.startsWith('#')?'comment':/^['"]/.test(value)?'str':/^\d/.test(value)?'num':'kw';html+='<span class="'+cls+'">'+escapeHTML(value)+'</span>';last=match.index+value.length;}html+=escapeHTML(code.slice(last))+'\n';$('highlight').innerHTML=html;$('lineNumbers').textContent=Array.from({length:code.split('\n').length},(_,i)=>i+1).join('\n');syncScroll();cursor();}
function syncScroll(){$('highlight').scrollTop=$('code').scrollTop;$('highlight').scrollLeft=$('code').scrollLeft;$('lineNumbers').scrollTop=$('code').scrollTop;}
function cursor(){const before=$('code').value.slice(0,$('code').selectionStart),parts=before.split('\n');$('cursorPosition').textContent=`Ln ${parts.length}, Col ${parts.at(-1).length+1} · UTF-8`;}
function changed(){const file=activeFile();if(!file)return;file.content=$('code').value;file.dirty=true;highlight();renderTabs();}
async function saveFile(path=state.active){if(!path)return;const file=state.files.get(path);const content=file.content;const result=await api('/api/save',{path,content,revision:file.revision});file.revision=result.revision;file.dirty=file.content!==content;renderTabs();}
function askText(title,value,action){$('textDialogTitle').textContent=title;$('textDialogInput').value=value;$('textDialogSubmit').onclick=guarded(async()=>{await action($('textDialogInput').value);$('textDialog').close();});$('textDialog').showModal();$('textDialogInput').focus();}
function newFile(content='# Новый Python-файл\n\nprint("Hello, Cosmos!")\n'){askText('Путь нового файла внутри проекта','hello.py',async path=>{path=path.trim();if(!path)throw new Error('Введите путь');if(state.files.has(path))throw new Error('Такой файл уже открыт');const result=await api('/api/save',{path,content,revision:null});state.files.set(path,{content,revision:result.revision,dirty:false});selectFile(path);await tree($('fileTree'));});}
async function poll(id,onUpdate){for(;;){const job=await api('/api/job?id='+id);onUpdate(job);if(job.status!=='running')return job;await new Promise(resolve=>setTimeout(resolve,500));}}
async function runFile(){if(state.run)return;if(!state.active?.endsWith('.py'))throw new Error('Откройте Python-файл');await saveFile();const {id}=await api('/api/run',{path:state.active,python:$('pythonPath').value});state.run=id;$('runFile').disabled=true;$('stopRun').disabled=false;$('runStatus').textContent='Выполняется…';try{const job=await poll(id,j=>{$('output').textContent=j.output||'Запуск…';$('output').scrollTop=$('output').scrollHeight;});$('runStatus').textContent=job.status==='cancelled'?'Остановлено':`Код завершения: ${job.code ?? 'ошибка'}`;}finally{state.run=null;$('runFile').disabled=false;$('stopRun').disabled=true;}}
function markdown(container,text){container.replaceChildren();const regex=/```[^\n]*\n([\s\S]*?)```/g;let last=0;for(const match of text.matchAll(regex)){if(match.index>last)container.append(el('p','',text.slice(last,match.index)));const block=el('div','code-block'),pre=el('pre','',match[1]),actions=el('div','code-actions');const copy=el('button','','Копировать'),insert=el('button','','Открыть как файл');copy.onclick=guarded(async()=>{await navigator.clipboard.writeText(match[1]);toast('Код скопирован');});insert.onclick=()=>newFile(match[1]);actions.append(copy,insert);block.append(pre,actions);container.append(block);last=match.index+match[0].length;}if(last<text.length)container.append(el('p','',text.slice(last)));}
function message(role,text,provider=state.provider){const item=el('div','message '+role);item.append(el('div','message-label',role==='user'?'ВЫ':provider.toUpperCase()));const body=el('div','message-body');if(role==='user')body.textContent=text;else markdown(body,text);item.append(body);$('messages').append(item);$('messages').scrollTop=$('messages').scrollHeight;return body;}
function renderChat(){$('messages').replaceChildren();for(const m of state.chats[state.provider])message(m.role,m.content);if(!state.chats[state.provider].length){const welcome=el('div','chat-welcome');welcome.append(el('div','spark',state.provider==='codex'?'✳':'✧'),el('h2','','Что создадим?'),el('p','','Объясню код, найду ошибку или помогу с новой функцией.'));$('messages').append(welcome);}}
function setProvider(provider){if(state.chat)return;state.provider=provider;$('codexProvider').classList.toggle('selected',provider==='codex');$('geminiProvider').classList.toggle('selected',provider==='gemini');$('editToggle').hidden=provider!=='codex';$('providerCaption').textContent=provider==='codex'?'Codex CLI · ваш аккаунт ChatGPT':'Gemini API · ваш ключ Google AI Studio';renderChat();}
async function sendChat(){if(state.chat)return;const text=$('prompt').value.trim();if(!text)return;const provider=state.provider;let content=text;const file=activeFile();if(file&&$('attachFile').checked)content+=`\n\nAttached file: ${state.active}\n\n${file.content}`;if(provider==='codex'&&$('allowEdits').checked){for(const [path,f] of state.files)if(f.dirty)await saveFile(path);}
const messages=[...state.histories[provider],{role:'user',content}];const {id}=await api('/api/chat',{provider,messages,key:$('geminiKey').value,model:$(provider+'Model').value,allowEdits:$('allowEdits').checked});state.chat=id;$('prompt').value='';$('sendChat').disabled=true;$('stopChat').disabled=false;$('newChat').disabled=true;$('codexProvider').disabled=true;$('geminiProvider').disabled=true;if(!state.chats[provider].length)$('messages').replaceChildren();state.chats[provider].push({role:'user',content:text});message('user',text);const body=message('assistant','Думаю…',provider);try{let previous='';const job=await poll(id,j=>{const value=j.answer||(j.output?'Работаю…\n'+j.output.slice(-1200):'Думаю…');if(value!==previous){markdown(body,value);previous=value;}});const answer=job.answer||(job.status==='cancelled'?'Запрос остановлен.':job.output||'Пустой ответ');markdown(body,answer);state.chats[provider].push({role:'assistant',content:answer});if(job.status==='done')state.histories[provider]=[...messages,{role:'assistant',content:answer}].slice(-16);else toast(job.status==='cancelled'?'Запрос остановлен':'Запрос завершился с ошибкой',job.status==='error');if(provider==='codex'&&$('allowEdits').checked){for(const [path,f] of state.files){if(!f.dirty){try{const updated=await api('/api/file?path='+encodeURIComponent(path));state.files.set(path,{...updated,dirty:false});}catch{}}}if(state.active)selectFile(state.active);await tree($('fileTree'));}}finally{state.chat=null;$('sendChat').disabled=false;$('stopChat').disabled=true;$('newChat').disabled=false;$('codexProvider').disabled=false;$('geminiProvider').disabled=false;}}
const statusNames={waiting:'Ожидает',running:'Работает',done:'Готово',error:'Ошибка',cancelled:'Остановлен'};
function renderTeam(){const root=el('div','org-root');function branch(node){const wrap=el('div','org-branch'),card=el('div','agent-card'),info=el('div','agent-info');info.append(el('div','agent-name',node.name),el('div','agent-role',(node.role||'Агент')+' · '+node.provider));const report=state.reports[node.id],status=report?.status||'waiting';const edit=el('button','','⚙');edit.title='Настроить роль';edit.disabled=!!state.teamJob;edit.onclick=()=>editAgent(node.id);card.append(el('div','agent-avatar',node.provider==='codex'?'✳':'✧'),info,el('span','agent-status '+status,statusNames[status]),edit);if(report?.answer){const show=el('button','','↗');show.title='Отчёт агента';show.onclick=()=>{ $('reportTitle').textContent=node.name;markdown($('reportContent'),report.answer);$('reportDialog').showModal();};card.append(show);}wrap.append(card);for(const child of state.team.filter(n=>n.parent===node.id))wrap.append(branch(child));return wrap;}const lead=state.team.find(n=>!n.parent);if(lead)root.append(branch(lead));$('orgTree').replaceChildren(root);}
function descendants(id){const set=new Set([id]);for(let i=0;i<state.team.length;i++)for(const n of state.team)if(set.has(n.parent))set.add(n.id);return set;}
function editAgent(id=null){const node=state.team.find(n=>n.id===id);$('agentId').value=id||'';$('agentName').value=node?.name||'';$('agentRole').value=node?.role||'';$('agentProvider').value=node?.provider||'codex';$('agentModel').value=node?.model||'';$('agentInstructions').value=node?.instructions||'';const parent=$('agentParent');parent.replaceChildren();const blocked=id?descendants(id):new Set();if(node?.parent===null||!state.team.length)parent.append(new Option('Нет — руководитель',''));for(const n of state.team)if(!blocked.has(n.id))parent.append(new Option(n.name,n.id));parent.value=node?node.parent||'':state.team[0]?.id||'';$('deleteAgent').disabled=!node||node.parent===null;$('agentDialog').showModal();}
async function saveAgent(){const old=$('agentId').value,id=old||crypto.randomUUID();const node={id,name:$('agentName').value.trim(),role:$('agentRole').value,provider:$('agentProvider').value,parent:$('agentParent').value||null,model:$('agentModel').value.trim(),instructions:$('agentInstructions').value};const nodes=old?state.team.map(n=>n.id===id?node:n):[...state.team,node];await api('/api/team/save',{nodes});state.team=nodes;state.teamDirty=false;renderTeam();$('agentDialog').close();}
async function deleteAgent(){const id=$('agentId').value;if(state.team.some(n=>n.parent===id))throw new Error('Сначала переназначьте или удалите подчинённых');const nodes=state.team.filter(n=>n.id!==id);await api('/api/team/save',{nodes});state.team=nodes;renderTeam();$('agentDialog').close();}
async function runTeam(){if(state.teamJob)return;let task=$('teamTask').value.trim();if(!task)throw new Error('Опишите задачу для команды');const file=activeFile();if(file&&$('attachFile').checked)task+=`\n\nAttached file: ${state.active}\n${file.content}`;await api('/api/team/save',{nodes:state.team});const {id}=await api('/api/team/run',{nodes:state.team,task,key:$('geminiKey').value});state.teamJob=id;$('runTeam').disabled=true;$('stopTeam').disabled=false;$('addAgent').disabled=true;$('teamSummary').textContent='Команда работает…';try{const job=await poll(id,j=>{state.reports=j.agents;renderTeam();});markdown($('teamSummary'),job.answer||job.output||'Остановлено');toast(job.status==='done'?'Команда завершила задачу':job.status==='cancelled'?'Команда остановлена':'Есть ошибки — проверьте отчёты агентов',job.status==='error');}finally{state.teamJob=null;$('runTeam').disabled=false;$('stopTeam').disabled=true;$('addAgent').disabled=false;renderTeam();}}
$('code').addEventListener('input',changed);$('code').addEventListener('scroll',syncScroll);$('code').addEventListener('click',cursor);$('code').addEventListener('keyup',cursor);$('code').addEventListener('keydown',e=>{const code=$('code');if(e.key==='Tab'){e.preventDefault();document.execCommand('insertText',false,'    ');}if(e.key==='Enter'&&!e.metaKey&&!e.ctrlKey){e.preventDefault();const line=code.value.slice(0,code.selectionStart).split('\n').at(-1),indent=line.match(/^\s*/)[0]+(line.trimEnd().endsWith(':')?'    ':'');document.execCommand('insertText',false,'\n'+indent);}});
$('newFile').onclick=()=>newFile();$('welcomeNew').onclick=()=>newFile();$('refreshFiles').onclick=guarded(()=>tree($('fileTree')));$('saveFile').onclick=guarded(async()=>{await saveFile();toast('Сохранено');});$('runFile').onclick=guarded(runFile);$('stopRun').onclick=guarded(()=>api('/api/stop',{id:state.run}));$('clearOutput').onclick=()=>$('output').textContent='';$('filesMode').onclick=()=>switchView(false);$('teamMode').onclick=()=>switchView(true);$('settingsButton').onclick=()=>$('settings').showModal();$('saveSettings').onclick=()=>{$('settings').close();$('pythonStatus').textContent=$('pythonPath').value;toast('Настройки применены');};$('sendChat').onclick=guarded(sendChat);$('stopChat').onclick=guarded(()=>api('/api/stop',{id:state.chat}));$('newChat').onclick=()=>{state.histories[state.provider]=[];state.chats[state.provider]=[];renderChat();};$('codexProvider').onclick=()=>setProvider('codex');$('geminiProvider').onclick=()=>setProvider('gemini');$('addAgent').onclick=()=>editAgent();$('saveAgent').onclick=guarded(saveAgent);$('deleteAgent').onclick=guarded(deleteAgent);$('saveTeam').onclick=guarded(async()=>{await api('/api/team/save',{nodes:state.team});toast('Дерево команды сохранено');});$('runTeam').onclick=guarded(runTeam);$('stopTeam').onclick=guarded(()=>api('/api/stop',{id:state.teamJob}));
function find(){if(!activeFile())return;askText('Поиск в открытом файле','',value=>{const code=$('code');let index=code.value.indexOf(value,code.selectionEnd);if(index<0)index=code.value.indexOf(value);if(index<0)throw new Error('Текст не найден');setTimeout(()=>{code.focus();code.setSelectionRange(index,index+value.length);code.scrollTop=Math.max(0,(code.value.slice(0,index).split('\n').length-3)*21);syncScroll();},0);});}
$('findButton').onclick=find;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.suggestion;$('prompt').focus();});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();guarded(saveFile)();}if((e.metaKey||e.ctrlKey)&&e.key==='f'&&!document.querySelector('dialog[open]')){e.preventDefault();find();}if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();guarded(document.activeElement===$('prompt')?sendChat:document.activeElement===$('teamTask')?runTeam:runFile)();}});
window.addEventListener('beforeunload',e=>{if([...state.files.values()].some(f=>f.dirty)){e.preventDefault();e.returnValue='';}});
guarded(async()=>{const info=await api('/api/info');$('workspace').textContent=info.root;$('projectName').textContent=info.name;$('pythonPath').value=info.python;$('pythonStatus').textContent=info.python;$('connectionStatus').textContent='Локально · подключено';$('codexStatus').textContent=info.codex?'Codex CLI подключён. Авторизация используется из вашего Codex.':'Codex CLI не найден. Установите CLI и выполните codex login.';if(info.geminiConfigured)$('geminiKey').placeholder='Используется ключ из окружения';state.team=await api('/api/team');renderTeam();await tree($('fileTree'));})().catch(()=>{});
