// Local development tools. Every process is created by an explicit user action.
const tools = {terminal:null, debug:null, panel:'output', breaks:{}, debugFrame:null, completion:null, selected:0, generation:0};
function cleanTerminal(value){return value.replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/\r/g,'');}
function outputText(id,text){const node=$(id),bottom=node.scrollHeight-node.scrollTop-node.clientHeight<40;node.textContent=cleanTerminal(text);if(bottom)node.scrollTop=node.scrollHeight;}
function toolPanel(name){tools.panel=name;for(const panel of ['output','terminal','debug']){$(panel+'Panel').hidden=panel!==name;$(panel+'Tab').classList.toggle('selected',panel===name);}}
async function terminalStart(){if(tools.terminal)return;const {id}=await api('/api/terminal/start',{});tools.terminal=id;try{const job=await poll(id,j=>outputText('terminalOutput',j.output));outputText('terminalOutput',job.output+'\n[Сеанс завершён]');}finally{if(tools.terminal===id)tools.terminal=null;}}
$('outputTab').onclick=()=>toolPanel('output');$('debugTab').onclick=()=>toolPanel('debug');$('terminalTab').onclick=()=>{toolPanel('terminal');if(!tools.terminal)guarded(terminalStart)();$('terminalInput').focus();};
$('terminalRestart').onclick=guarded(async()=>{if(tools.terminal)await api('/api/stop',{id:tools.terminal});tools.terminal=null;await terminalStart();});
$('terminalInputForm').onsubmit=e=>{e.preventDefault();guarded(async()=>{if(!tools.terminal)throw new Error('Откройте новый сеанс терминала');const text=$('terminalInput').value;$('terminalInput').value='';await api('/api/session/input',{id:tools.terminal,text:text+'\n'});})();};
$('terminalInterrupt').onclick=guarded(()=>api('/api/session/input',{id:tools.terminal,text:'\x03'}));$('terminalEof').onclick=guarded(()=>api('/api/session/input',{id:tools.terminal,text:'\x04'}));
// A focused output area also accepts raw keyboard input for interactive programs.
$('terminalOutput').onkeydown=e=>{if(!tools.terminal||e.metaKey||e.key==='Tab')return;let text=e.ctrlKey&&e.key.toLowerCase()==='c'?'\x03':e.ctrlKey&&e.key.toLowerCase()==='d'?'\x04':e.key==='Enter'?'\n':e.key==='Backspace'?'\x7f':e.key.length===1&&!e.ctrlKey?e.key:null;if(text){e.preventDefault();guarded(()=>api('/api/session/input',{id:tools.terminal,text}))();}};
$('programInputForm').onsubmit=e=>{e.preventDefault();guarded(async()=>{if(!state.run)throw new Error('Программа не запущена');await api('/api/session/input',{id:state.run,text:$('programInput').value+'\n'});$('programInput').value='';})();};
function breakpoints(){return Object.fromEntries(Object.entries(tools.breaks).filter(([p,lines])=>lines.size).map(([p,lines])=>[p,[...lines].sort((a,b)=>a-b)]));}
function paintBreakpoints(){document.querySelectorAll('.line-number').forEach(n=>{const line=Number(n.dataset.line);n.classList.toggle('breakpoint',!!tools.breaks[state.active]?.has(line));n.classList.toggle('debug-line',tools.debugFrame?.path===state.active&&tools.debugFrame.line===line);n.title='Точка остановки — нажмите';});}
window.paintBreakpoints=paintBreakpoints;
$('lineNumbers').onclick=guarded(async e=>{const n=e.target.closest('.line-number');if(!n||!state.active?.endsWith('.py'))return;const set=tools.breaks[state.active] ||= new Set(),line=Number(n.dataset.line);set.has(line)?set.delete(line):set.add(line);paintBreakpoints();if(tools.debug)await api('/api/debug/action',{id:tools.debug,action:'breakpoints',breakpoints:breakpoints()});});
async function debugAction(action){if(!tools.debug)throw new Error('Сначала запустите отладку');await api('/api/debug/action',{id:tools.debug,action});}
function debugButtons(debug){document.querySelectorAll('[data-debug]').forEach(b=>b.disabled=!tools.debug||(['continue','step','next','out'].includes(b.dataset.debug)&&debug.state!=='paused'));$('debugStop').disabled=!tools.debug;}
async function debugFrame(frame){if(!frame.path)return;await openFile(frame.path);tools.debugFrame=frame;paintBreakpoints();$('code').scrollTop=Math.max(0,(frame.line-4)*21);syncScroll();}
async function runPython(debug){if(state.run||tools.debug)throw new Error('Сначала остановите текущий запуск');if(!state.active?.endsWith('.py'))throw new Error('Откройте Python-файл');for(const [path,file] of state.files)if(file.dirty)await saveFile(path);const data={path:state.active,python:$('pythonPath').value,args:$('runArgs').value,breakpoints:breakpoints()};const {id}=await api(debug?'/api/debug/start':'/api/run',data);if(debug)tools.debug=id;else state.run=id;$('code').readOnly=debug;toolPanel(debug?'debug':'output');$('runFile').disabled=$('debugFile').disabled=true;$('stopRun').disabled=debug;$('runStatus').textContent=debug?'Отладка…':'Выполняется…';let sequence=-1;try{const job=await poll(id,j=>{outputText(debug?'debugOutput':'output',j.output);if(debug){const d=j.debug;debugButtons(d);$('debugInputForm').hidden=d.state!=='input';$('debugStatus').textContent=d.state==='paused'?`${d.reason==='exception'?'Исключение · ':''}${d.path}:${d.line}`:d.state==='input'?'Ожидается ввод программы':d.state==='running'?'Выполняется…':'Завершено';if(d.state==='paused'&&sequence!==d.sequence){sequence=d.sequence;tools.debugFrame={path:d.path,line:d.line};$('debugLocals').textContent=Object.entries(d.locals||{}).map(([k,v])=>k+' = '+v).join('\n')||'Нет локальных переменных';$('debugStack').replaceChildren(...(d.frames||[]).map(frame=>{const b=el('button','stack-frame',`${frame.name} · ${frame.path}:${frame.line}`);b.onclick=guarded(()=>debugFrame(frame));return b;}));guarded(()=>debugFrame(tools.debugFrame))();}else if(d.state==='running'){tools.debugFrame=null;paintBreakpoints();}}});$('runStatus').textContent=job.status==='cancelled'?'Остановлено':`Код завершения: ${job.code ?? 'ошибка'}`;}finally{if(debug)tools.debug=null;else state.run=null;$('code').readOnly=false;tools.debugFrame=null;paintBreakpoints();debugButtons({state:'done'});$('runFile').disabled=$('debugFile').disabled=false;$('stopRun').disabled=true;}}
$('debugFile').onclick=guarded(()=>runPython(true));document.querySelectorAll('[data-debug]').forEach(b=>b.onclick=guarded(()=>debugAction(b.dataset.debug)));$('debugStop').onclick=guarded(()=>api('/api/stop',{id:tools.debug}));
$('debugInputForm').onsubmit=e=>{e.preventDefault();guarded(async()=>{await api('/api/session/input',{id:tools.debug,text:$('debugInput').value});$('debugInput').value='';})();};
document.addEventListener('keydown',e=>{if(e.key==='F5'){e.preventDefault();guarded(()=>tools.debug?debugAction('continue'):runPython(true))();}if(tools.debug&&['F10','F11'].includes(e.key)){e.preventDefault();guarded(()=>debugAction(e.key==='F10'?'next':e.shiftKey?'out':'step'))();}});
// Completion requests use UTF-16 <-> Unicode offsets explicitly for non-BMP text.
let hintTimer;
function closeCompletion(){tools.completion=null;$('completionMenu').hidden=true;tools.generation++;$('code').setAttribute('aria-expanded','false');}
function renderCompletion(){const menu=$('completionMenu'),list=tools.completion?.items||[];menu.replaceChildren();list.forEach((item,i)=>{const button=el('button',i===tools.selected?'selected':'');button.setAttribute('role','option');button.setAttribute('aria-selected',String(i===tools.selected));button.append(el('span','',item.label),el('small','',item.kind));button.title=item.detail;button.onmousedown=e=>{e.preventDefault();insertCompletion(i);};menu.append(button);});if(list.length){const detail=el('div','completion-detail',list[tools.selected].detail||'Enter / Tab — вставить · Esc — закрыть');menu.append(detail);}menu.hidden=!list.length;$('code').setAttribute('aria-expanded',String(!!list.length));}
async function hints(force=false){const code=$('code');if(!state.active?.endsWith('.py'))return;const end=code.selectionStart,before=code.value.slice(0,end);if(!force&&!/[A-Za-z_.]$/.test(before)){closeCompletion();return;}const source=code.value,file=state.active,generation=++tools.generation;const result=await api('/api/completion',{source,offset:Array.from(before).length});if(generation!==tools.generation||code.value!==source||code.selectionStart!==end||state.active!==file)return;result.start=Array.from(source).slice(0,result.start).join('').length;result.end=end;tools.completion=result;tools.selected=0;renderCompletion();}
function insertCompletion(i){const completion=tools.completion;if(!completion)return;const code=$('code');code.focus();code.setSelectionRange(completion.start,completion.end);document.execCommand('insertText',false,completion.items[i].label);closeCompletion();}
function completionKey(e){if(e.ctrlKey&&e.code==='Space'){e.preventDefault();guarded(()=>hints(true))();return true;}const completion=tools.completion;if(!completion?.items.length)return false;if(['ArrowDown','ArrowUp','Enter','Tab','Escape'].includes(e.key)){e.preventDefault();if(e.key==='Escape')closeCompletion();else if(e.key==='Enter'||e.key==='Tab')insertCompletion(tools.selected);else{tools.selected=(tools.selected+(e.key==='ArrowDown'?1:-1)+completion.items.length)%completion.items.length;renderCompletion();}return true;}if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key))closeCompletion();return false;}
window.completionKey=completionKey;$('code').setAttribute('aria-autocomplete','list');$('code').setAttribute('aria-controls','completionMenu');$('code').addEventListener('input',()=>{clearTimeout(hintTimer);hintTimer=setTimeout(()=>guarded(hints)(),140);});$('code').addEventListener('blur',closeCompletion);$('code').addEventListener('click',closeCompletion);debugButtons({state:'done'});
